# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  node: circleci/node@4.1
  cypress: cypress-io/cypress@1

machine:
  environment:
    BROWSERSTACK_USERNAME: "browserstack_8Pp0mQ"
    BROWSERSTACK_ACCESS_KEY: "QgFfrZpnNaMzAgvZeaTa"
    BROWSERSTACK_LOCAL: true
test:
    pre:
    # Download the browserstack binary file
    - wget "https://www.browserstack.com/browserstack-local/BrowserStackLocal-linux-x64.zip"
    # Unzip the BrowserStack Local binary file
    - unzip BrowserStackLocal-linux-x64.zip
    # Run the file with your access key
    - ./BrowserStackLocal $BROWSERSTACK_ACCESS_KEY:
        background: true

workflows:
  sample:
    jobs:
      - node/test:
          version: '15.1'
          # This is the node version to use for the `cimg/node` tag
          # Relevant tags can be found on the CircleCI Developer Hub
          # https://circleci.com/developer/images/image/cimg/node
