# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  cypress: cypress-io/cypress@1
  
workflows:
  build:
    jobs:
      - cypress/run:
          record: true
  
machine:
  environment:
    BROWSERSTACK_USERNAME: "browserstack_8Pp0mQ"
    BROWSERSTACK_ACCESS_KEY: "QgFfrZpnNaMzAgvZeaTa"
    BROWSERSTACK_LOCAL: true
test:
    pre:
    # Download the browserstack binary file
    - wget "https://www.browserstack.com/browserstack-local/BrowserStackLocal-linux-x64.zip"
    # Unzip the BrowserStack Local binary file
    - unzip BrowserStackLocal-linux-x64.zip
    # Run the file with your access key
    - ./BrowserStackLocal $BROWSERSTACK_ACCESS_KEY:
        background: true
